name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Setup Cosign
        run: |
          echo "${COSIGN_KEY}" > "$GITHUB_WORKSPACE/cosign.key"
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref , 'refs/tags/v') == true
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Run GoReleaser in Snapshot Mode
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref , 'refs/tags/v') == false
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Push Snapshot Docker Image
        if: startsWith(github.ref , 'refs/tags/v') == false
        run: |
          docker push $(docker images -a  | grep dockit | awk '{ print $1 ":" $2 }')
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref , 'refs/tags/v') == false
        with:
          name: release
          path: |
            release/*.tar.gz
            release/config.yaml
            release/checksums.txt
